
shallow_clone: true

environment:

  global:
    NSIS_DIR: "%PROGRAMFILES(x86)%/NSIS"
    MPLBACKEND: "agg"

  matrix:
     - PYTHON: "C:\\Miniconda37-x64"
       PYTHON_VERSION_SHORT: "37"
       PYTHON_VERSION: "3.7.4"
       PYTHON_ARCH: "64"
       WP_URL: 'https://downloads.sourceforge.net/project/winpython/WinPython_3.7/3.7.4.0/Winpython64-3.7.4.0.exe'
       WP_CRC: '5701b68128a69926f8b7a136fc3e3b1e0b64b07e6ccb21d1995db3d879617a49'
       WP_DIR_NAME: 'WPy64-3740'

     - PYTHON: "C:\\Miniconda37"
       PYTHON_VERSION_SHORT: "37"
       PYTHON_VERSION: "3.7.4"
       PYTHON_ARCH: "32"
       WP_URL: 'https://downloads.sourceforge.net/project/winpython/WinPython_3.7/3.7.4.0/Winpython32-3.7.4.0.exe'
       WP_CRC: '0a53bba8d413278317fa5d5a886973123cad9b2ba837a979b4337464c74fad6a'
       WP_DIR_NAME: 'WPy32-3740'

init:
  - "ECHO %PYTHON% %PYTHON_VERSION% %PYTHON_ARCH%"
  - "ECHO %APPVEYOR_BUILD_FOLDER%"

install:
  - ps: Add-AppveyorMessage "Installing hyperspy-bundle..."
  - "%PYTHON%/Scripts/pip install ."

build: false  # Not a C# project, build stuff at the test step instead.

  # Build bundle installer for tags:
before_deploy:
  # Download WinPython installer if not cached
  - ps: Add-AppveyorMessage "Installing WinPython..."
  - "SET WP_DIR=%USERPROFILE%/%WP_DIR_NAME%"
  - "SET WP_EXE=%USERPROFILE%/WinPython3.exe"
  - ps: appveyor DownloadFile $Env:WP_URL -FileName $Env:WP_EXE
  - ps: Write-Output (Get-FileHash $Env:WP_EXE)
  - ps: if ((Get-FileHash $Env:WP_EXE).Hash -ne $Env:WP_CRC) { exit(1) }
  - ps: (& $Env:WP_EXE -y | Out-Null )
  - "ls"
  - "ls %USERPROFILE%"
  - "ls %WP_DIR%"

  # Install UAC plugin
  - ps: Add-AppveyorMessage "Setting up WinPython environment..."
  - ps: Start-FileDownload ('http://nsis.sourceforge.net/mediawiki/images/8/8f/UAC.zip') ../UAC.zip
  - ps: if ((Get-FileHash '../UAC.zip').Hash -ne '20E3192AF5598568887C16D88DE59A52C2CE4A26E42C5FB8BEE8105DCBBD1760') { exit(1) }
  - "7z x ../UAC.zip -o%NSIS_DIR% -aoa"

  # Install current hyperspy in WinPython
  - "%WP_DIR%/scripts/env.bat"
  # Give info about python vesion and compiler used to compile the python
  - "python.exe -c \"import sys; print(sys.version)\""

  # Remove some large package to get below the NSIS 2Gb limit
  - "pip uninstall -y tensorflow tensorflow_estimator tensorflow_probability torch torchvision"

  # Use a specific branch of hyperspy on github
  #- "pip install https://github.com/francisco-dlp/hyperspy/archive/v1.4.1.zip#egg=hyperspy[all]"
  # Use a release version of hyperspy
  - "pip install hyperspy[all]"
  - "pip install start_jupyter_cm hyperspyui atomap pixstem pyxem"

  # Clean python cache (*.pyc files and __pycache__ folders) shipped with winpython
  - "pip install pycleanup"
  - "pushd %WP_DIR% & pycleanup --cache & popd"

  # Custom installer step
  - ps: Add-AppveyorMessage "Creating installer..."
  - ps: 'Get-ChildItem -Recurse $Env:WP_DIR | Measure-Object -Property Length -Sum'
  - "%PYTHON%/python.exe -m hspy_bundle.configure_installer %USERPROFILE% %PYTHON_ARCH% %APPVEYOR_REPO_TAG_NAME%"
  - "\"%NSIS_DIR%/makensis.exe\" /V3 NSIS_installer_script-%PYTHON_ARCH%bit.nsi"
  - "ls"
  # Use hyperspy-bundle tag as version name
  - "SET BUNDLE_INST_NAME=HyperSpy-Bundle-%APPVEYOR_REPO_TAG_NAME%-py%PYTHON_VERSION_SHORT%-%PYTHON_ARCH%bit.exe"
  - "ren HyperSpy-Bundle-%APPVEYOR_REPO_TAG_NAME%-%PYTHON_ARCH%bit.exe %BUNDLE_INST_NAME%"

  - ps: Add-AppveyorMessage "Pushing artefacts..."
  - "appveyor PushArtifact %BUNDLE_INST_NAME%"
  # Report checksums
  - md5sum %BUNDLE_INST_NAME%
  - sha256sum %BUNDLE_INST_NAME%

  - ps: Add-AppveyorMessage "Installer created! Run tests in Winpython environment..."
  # Re-run tests in WinPython environment
  - "pip install pytest pytest-mpl pytest-qt"
  - "pytest --mpl --pyargs hyperspy"
  # FIXME the test suite hold the build
  # - "pytest --pyargs hyperspyui"
  - "pytest --pyargs atomap"
  - "pytest --pyargs pyxem"

deploy:
  provider: GitHub
  auth_token:
    #   to266:
    #secure: ptV5Dkz3pSVdjD0qRDpxJgjVlddFtleZ+B+c2X1Fg67P8OX3bHWVktRmlj6hfLhM
    #   vidartf:
    #secure: KwAfARhGEqOnZHltPB6kKu8xmnoiGSk7NMYJBIEbWvFCuVnepoPV7ZcIjUN3pUpK
    #   sem-geologist:
    #secure: RRqUkx9H5VuFNITmm+YzgB0qnqgVGPH1yrPVxb4oCD+FAjcTch2WZAiPEKn4L6w6
    #   ericpre:
    secure: ae8XsPI+vKJI9AWm0r9+ec71CIkXcnCHlNIQ57v+87hh5k1xuAAxIOi1CFKEmmZv
  artifact: /.*\.exe/  # upload installers to release assets
  draft: false
  prerelease: false
  force_update: true
  on:
    appveyor_repo_tag: true        # deploy on tag push only
