
shallow_clone: true

environment:

  global:
    MINICONDA: "C:\\Miniconda37"

  matrix:

    # Pre-installed Python versions, which Appveyor may upgrade to
    # a later point release.
     - PYTHON_VERSION_SHORT: "36"
       PYTHON_VERSION: "3.6.6"
       PYTHON_ARCH: "32"
       WP_URL: 'https://github.com/winpython/winpython/releases/download/1.10.20180827/WinPython32-3.6.6.2Qt5.exe'
       WP_CRC: 'af9301f4748f7443732c6fc2ecab0e25e0109d5fda623d686e4371d015eb7be3'

     - PYTHON_VERSION_SHORT: "36"
       PYTHON_VERSION: "3.6.6"
       PYTHON_ARCH: "64"
       WP_URL: 'https://github.com/winpython/winpython/releases/download/1.10.20180827/WinPython64-3.6.6.2Qt5.exe'
       WP_CRC: '0007085df58ad4e5749e6d3fc43ce49688ca15a77abea615d36770b2f7ec1ba3'

     - PYTHON_VERSION_SHORT: "37"
       PYTHON_VERSION: "3.7.0"
       PYTHON_ARCH: "32"
       WP_URL: 'https://github.com/winpython/winpython/releases/download/1.10.20180827/WinPython32-3.7.0.2.exe'
       WP_CRC: '4516e09e671d027d50f0c160ad9d2fe8528f610970d38a20093fbdcc731b0735'

     - PYTHON_VERSION_SHORT: "37"
       PYTHON_VERSION: "3.7.0"
       PYTHON_ARCH: "64"
       WP_URL: 'https://github.com/winpython/winpython/releases/download/1.10.20180827/WinPython64-3.7.0.2.exe'
       WP_CRC: '506376156017929982179381bf449841fb17041f0d95ea03ed4c8add871e8f45'

init:
  - "ECHO %PYTHON_VERSION% %PYTHON_ARCH%"
  - "ECHO %APPVEYOR_BUILD_FOLDER%"
  - "ECHO %CMD_IN_ENV%"

install:
  - ps: Add-AppveyorMessage "Installing hyperspy-bundle..."
  - "%MINICONDA%/Scripts/pip install ."

build: false  # Not a C# project, build stuff at the test step instead.

  # Build bundle installer for tags:
before_deploy:
  # Download WinPython installer if not cached
  - ps: Add-AppveyorMessage "Installing WinPython..."
  - "SET WP_INSTDIR=%USERPROFILE%\\wpdir\\WinPython-%PYTHON_ARCH%\\"
  - "SET WP_EXE=%USERPROFILE%/wpdir/WinPython3-%PYTHON_ARCH%bit.exe"
  - "mkdir %USERPROFILE%\\wpdir"
  - ps: appveyor DownloadFile $Env:WP_URL -FileName $Env:WP_EXE
  - ps: Write-Output (Get-FileHash $Env:WP_EXE)
  - ps: if ((Get-FileHash $Env:WP_EXE).Hash -ne $Env:WP_CRC) { exit(1) }
  - ps: (& $Env:WP_EXE /S /D=$Env:WP_INSTDIR | Out-Null )
  - "ls %USERPROFILE%/wpdir"
  - "ls %WP_INSTDIR%"

  # Install current hyperspy in WinPython
  - "%CMD_IN_ENV% %WP_INSTDIR%/scripts/env.bat"
  # Give info about python vesion and compiler used to compile the python
  - "%CMD_IN_ENV% python.exe -c \"import sys; print(sys.version)\""

  # Remove typing to run tests (winpython bug?) typing is only requires for python<3.5
  - "%CMD_IN_ENV% pip uninstall -y typing"
  # tqdm RuntimeError when running samfire tests, see https://github.com/hyperspy/hyperspy/issues/2077
  - "%CMD_IN_ENV% pip install tqdm==4.24"
  # Use a specific branch of hyperspy on github
  #- "%CMD_IN_ENV% pip install https://github.com/francisco-dlp/hyperspy/archive/v1.4.1.zip#egg=hyperspy[all]"
  # Use a release version of hyperspy
  - "%CMD_IN_ENV% pip install hyperspy[all]"
  - "%CMD_IN_ENV% pip install start_jupyter_cm"
  # Try to run twice as workaround for permission error (for now, we keep master to test the bundle)
  - "%CMD_IN_ENV% pip install https://github.com/hyperspy/hyperspyUI/archive/master.zip || pip install https://github.com/hyperspy/hyperspyUI/archive/master.zip"

  # Custom installer step
  - ps: Add-AppveyorMessage "Creating installer..."
  - "ECHO %PATH%"
  # prepend PATH to use makensis from miniconda
  - "SET PATH=%MINICONDA%;%PATH%"
  - "ECHO %PATH%"
  - "%MINICONDA%/python.exe -m hspy_bundle.configure_installer %USERPROFILE%/wpdir %PYTHON_ARCH% %APPVEYOR_REPO_TAG_NAME%"
  - "%MINICONDA%/Scripts/conda.exe install -yq -c conda-forge conda-execute"
  - "%MINICONDA%/Scripts/conda.exe execute -v NSIS_installer_script-%PYTHON_ARCH%bit.nsi"
  - "ls"
  - ps: Add-AppveyorMessage "Installer created! Run tests in Winpython environment..."
  # Re-run tests in WinPython environment
  # Use matplotlib 2.2.3 until tests are not compatible with 3.0
  - "%CMD_IN_ENV% pip install matplotlib==2.2.3 pytest-mpl"
  - ps: if($Env:PYTHON_ARCH -eq "64") {$Env:PYTHON_DIR_NAME="python-"+$Env:PYTHON_VERSION+".amd64"} else {$Env:PYTHON_DIR_NAME="python-"+$Env:PYTHON_VERSION}
  # Use hyperspy-bundle tag as version name
  - "SET BUNDLE_INST_NAME=HyperSpy-Bundle-%APPVEYOR_REPO_TAG_NAME%-py%PYTHON_VERSION_SHORT%-%PYTHON_ARCH%bit.exe"
  - "ren HyperSpy-Bundle-%APPVEYOR_REPO_TAG_NAME%-%PYTHON_ARCH%bit.exe %BUNDLE_INST_NAME%"
  - "SET HYPERSPY_DIR=%WP_INSTDIR%\\%PYTHON_DIR_NAME%\\Lib\\site-packages\\hyperspy"
  - ps: pytest --mpl $Env:HYPERSPY_DIR
  - ps: Add-AppveyorMessage "Tests finished! Pushing to GitHub..."
  - "appveyor PushArtifact %BUNDLE_INST_NAME%"

on_failure:
  # In case, the tests fail, we still push the installer to debug the failure if necessary.
  - "appveyor PushArtifact %BUNDLE_INST_NAME%"

deploy:
  provider: GitHub
  auth_token:
    #   to266:
    #secure: ptV5Dkz3pSVdjD0qRDpxJgjVlddFtleZ+B+c2X1Fg67P8OX3bHWVktRmlj6hfLhM
    #   vidartf:
    #secure: KwAfARhGEqOnZHltPB6kKu8xmnoiGSk7NMYJBIEbWvFCuVnepoPV7ZcIjUN3pUpK
    #   sem-geologist:
    #secure: RRqUkx9H5VuFNITmm+YzgB0qnqgVGPH1yrPVxb4oCD+FAjcTch2WZAiPEKn4L6w6
    #   ericpre:
    secure: ae8XsPI+vKJI9AWm0r9+ec71CIkXcnCHlNIQ57v+87hh5k1xuAAxIOi1CFKEmmZv
  artifact: /.*\.exe/  # upload installers to release assets
  draft: false
  prerelease: false
  force_update: true
  on:
    appveyor_repo_tag: true        # deploy on tag push only
