name: Release

on:
  workflow_dispatch:
    workflow: "*"
  push:
    branches:
      - '*'
    tags:
      - '*'
  pull_request:
    branches:
      - main

permissions:
  # needs write permission at workflow level to create release and upload artifacts
  contents: write

jobs:
  create_release_job:
    name: Create Release (on tag only)
    runs-on: ubuntu-latest
    outputs: 
      upload_url: ${{ steps.create_release.outputs.upload_url }}
      VERSION: ${{ env.VERSION }}
    steps:
      - uses: actions/checkout@v2

      - name: Get version (on tag)
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          echo "VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Get version (short hash)
        if: "!startsWith(github.ref, 'refs/tags/')"
        run: |
          # Use git short hash instead of tag
          echo "VERSION=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Display version
        run: |
          echo ${{ env.VERSION }}

      - name: Find and Replace
        uses: jacobtomlinson/gha-find-replace@0.1.4
        if: startsWith(github.ref, 'refs/tags/')
        with:
          find: "__TAG__"
          replace: ${{ env.VERSION }}
          include: "RELEASE_TEXT.md" # Will match all RELEASE_TEXT.md files in any nested directory

      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/')
        id: create_release
        uses: softprops/action-gh-release@v0.1.7
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions
        with:
          body_path: "RELEASE_TEXT.md"
          prerelease: true


  build:
    name: ${{ matrix.os }}-${{ matrix.BLAS_IMPL }}
    needs: create_release_job
    runs-on: ${{ matrix.os }}-latest
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu, windows, macos]
        BLAS_IMPL: [mkl, openblas]
        include:
          - os: ubuntu
            INSTALLER_EXTENSION: sh
          - os: windows
            INSTALLER_EXTENSION: exe
          - os: macos
            INSTALLER_EXTENSION: pkg
        exclude:
          - os: macos
            BLAS_IMPL: openblas
    env:
      TEST_DEPS: pytest pytest-qt
      LIB_TO_TEST: atomap pyxem kikuchipy
      DISPLAY: :0

    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: 3.9
          miniforge-version: latest

      - shell: bash -l {0}
        name: Conda info
        run: |
          conda info
          conda list

      - shell: bash -l {0}
        name: Install constructor
        run: |
          conda install constructor jinja2

      - shell: bash -l {0}
        name: Build distribution
        env:
          VERSION: ${{ needs.create_release_job.outputs.VERSION }}
          BLAS_IMPL: ${{ matrix.BLAS_IMPL }}
        run: |
          conda config --set channel_priority strict
          constructor -v conda_distribution

      - shell: bash -l {0}
        name: Set asset name
        env:
          ext: ${{ matrix.INSTALLER_EXTENSION }}
        run: |  
          installer_name=(HyperSpy-*.${{ env.ext }})
          echo "Original installer name: " $installer_name
          # Rename installer name according to BLAS_IMPL
          if [ ${{ matrix.BLAS_IMPL }} = mkl ]; then
             CPU=Intel
          else
             CPU=AMD
          fi    
          new_installer_name=$(basename $installer_name .${{ env.ext }})-$CPU.${{ env.ext }}   
          mv $installer_name $new_installer_name
          echo "asset_name=$new_installer_name" >> $GITHUB_ENV
          echo "Installer name: "$new_installer_name
          ls

      - name: Get hash
        run: |
          shasum -a 256 ${{ env.asset_name }}

      - name: Install new distribution (Linux)
        if: runner.os == 'linux'
        env:
          install_dir: '${{ github.workspace }}/new_distribution'
        run: |
          echo "install_dir=${{ env.install_dir }}" >> $GITHUB_ENV
          bash ${{ env.asset_name }} -b -p ${{ env.install_dir }}

      - name: Install new distribution (MacOS)
        if: runner.os == 'macos'
        run: |
          echo "install_dir=/Users/runner" >> $GITHUB_ENV
          installer -pkg ${{ env.asset_name }} -target CurrentUserHomeDirectory

      - name: Install new distribution (Windows)
        if: runner.os == 'windows'
        env:
          install_dir: '${{ github.workspace }}\nd'
        shell: bash
        run: |
          echo "install_dir=${{ env.install_dir }}" >> $GITHUB_ENV

      - name: Install new distribution (Windows)
        if: runner.os == 'windows'
        shell: powershell
        run: |
          Start-Process -Wait -FilePath ${{ env.asset_name }} -ArgumentList "/S /AddToPath=0 /RegisterPython=0 /NoScripts=1 /D=${{ env.install_dir }}"

      - name: Upload artifact
        if: startsWith(github.ref, 'refs/tags/') != true
        uses: actions/upload-artifact@v2
        with:
          path: ${{ env.asset_name }}
          name: ${{ env.asset_name }}

      - shell: bash -l {0}
        name: Info new distribution
        run: |
          conda activate "${{ env.install_dir }}"
          conda info
          conda config --show channels
          conda config --show channel_priority
          conda list

      - shell: bash -l {0}
        name: Check latest available hyperspy version
        run: |
          conda activate "${{ env.install_dir }}"     
          conda install johnnydep
          python check_hyperspy_latest.py

      - name: Install xvfb
        if: runner.os == 'linux' && always()
        run: |
          sudo apt-get install -y xvfb libxkbcommon-x11-0 libxcb-icccm4 libxcb-image0 libxcb-keysyms1 libxcb-randr0 libxcb-render-util0 libxcb-xinerama0 libxcb-xinput0 libxcb-xfixes0

      - name: Start xvfb
        if: runner.os == 'linux' && always()
        run: |
          sudo /usr/bin/Xvfb ${{ env.DISPLAY }} -screen 0 1280x1024x24 & 

      - shell: bash -l {0}
        name: Install test dependencies
        if: always()
        run: |
          conda activate "${{ env.install_dir }}"
          conda install ${{ env.TEST_DEPS }}

      - shell: bash -l {0}
        # TODO: revisit at some point, to get it to work on linux (hyperspyui CI works fine...)
        if: runner.os != 'linux' && always()
        name: Test new distribution (HyperSpyUI)
        run: |
          conda activate "${{ env.install_dir }}"
          pytest --pyargs hyperspyui

      - shell: bash -l {0}
        name: Test hyperspy
        if: always()
        env:
          MPLBACKEND: 'agg'
        run: |
          conda activate "${{ env.install_dir }}"
          pytest --pyargs hyperspy

      - shell: bash -l {0}
        name: Run other test suites
        if: always()
        env:
          MPLBACKEND: 'agg'
        run: |
          conda activate "${{ env.install_dir }}"
          pytest --pyargs ${{ env.LIB_TO_TEST }}

      - name: Upload Release Asset
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v0.1.7
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: ${{ env.asset_name }}
          prerelease: true


  build_portable:
    name: windows (Portable)
    needs: create_release_job
    runs-on: windows-latest
    env:
      # when updating winpython version, check status of https://github.com/dask/dask/issues/7583
      # to know if dask needs to be downgraded
      WP_URL: https://github.com/winpython/winpython/releases/download/4.3.20210620/Winpython64-3.9.5.0.exe
      WP_SHA256: 9a2f25ee58a35656a06bafeddba87c47de28cf11931cdbafe0ebd5b5a4eac2d5
      WP_EXE: winpython.exe
      WP_DIR_NAME: WPy64-3950
      TEST_DEPS: pytest pytest-qt
      LIB_TO_INSTALL: hyperspy[all] hyperspyui pyxem atomap kikuchipy pystackreg matplotlib-scalebar start_jupyter_cm particlespy nglview scanning_drift_corr hdf5plugin dask-labextension graphviz abtem
      LIB_TO_TEST: atomap pyxem kikuchipy

    steps:
      - uses: actions/checkout@v2
      - name: Download Winpython
        run: |
          Invoke-WebRequest -OutFile ${{ env.WP_EXE }} ${{ env.WP_URL }}
          ls
          $file_hash = (Get-FileHash ${{ env.WP_EXE }} ).Hash
          $file_hash 
          if ($file_hash -ne "${{ env.WP_SHA256 }}") { exit(1) }

      - name: Install Winpython
        run: |
          .\${{ env.WP_EXE }} -y | Out-Null
          ls
          ls ${{ env.WP_DIR_NAME }}

      - name: Install libraries
        shell: cmd
        run: |
          call "${{ env.WP_DIR_NAME }}\scripts\env.bat"
          where python
          where pip
          # pin dask until https://github.com/dask/dask/issues/7583 is fixed
          # and the dask version (2021.9.0) in winpython includes the bug fix 
          pip install dask>=2021.9.0 distributed>=2021.9.0
          pip install ${{ env.LIB_TO_INSTALL }}

      - shell: bash -l {0}
        name: Set installer name
        env:
          VERSION: ${{ needs.create_release_job.outputs.VERSION }}
        run: |
          installer_name=HyperSpy-bundle-${{ env.VERSION }}-Windows-x86_64-Portable.exe
          echo "asset_name=$installer_name" >> $GITHUB_ENV
          echo $installer_name

      - name: Run pyclean in distribution folder
        shell: cmd
        run: |
          where pip
          pip install pyclean
          where pyclean
          pyclean ${{ env.WP_DIR_NAME }}

      - name: Create installer
        run: |
          7z -mx5 -sfx a ${{ env.asset_name }} ${{ env.WP_DIR_NAME }}
          ls

      - name: Upload artifact
        if: startsWith(github.ref, 'refs/tags/') != true
        uses: actions/upload-artifact@v2
        with:
          path: ${{ env.asset_name }}
          name: ${{ env.asset_name }}

      - name: Install new distribution
        run: |
          Remove-Item -recurse ${{ env.WP_DIR_NAME }}
          ls
          .\${{ env.asset_name }} -y | Out-Null
          echo "After installation"
          ls
          echo ${{ env.asset_name }}

      - name: Check latest available hyperspy version
        shell: cmd
        run: |
          call "${{ env.WP_DIR_NAME }}\scripts\env.bat"
          pip install johnnydep
          python check_hyperspy_latest.py

      - name: Install testing libraries
        if: always()
        shell: cmd
        run: |
          call "${{ env.WP_DIR_NAME }}\scripts\env.bat"
          pip install ${{ env.TEST_DEPS }}

      - name: Run test suite (HyperSpyUI)
        if: always()
        shell: cmd
        run: |
          call "${{ env.WP_DIR_NAME }}\scripts\env.bat"
          pytest --pyargs hyperspyui

      - name: Run test hyperspy
        if: always()
        shell: cmd
        env:
          MPLBACKEND: 'agg'
        run: |
          call "${{ env.WP_DIR_NAME }}\scripts\env.bat"
          pytest --pyargs hyperspy

      - name: Run other test suites
        if: always()
        shell: cmd
        env:
          MPLBACKEND: 'agg'
        run: |
          call "${{ env.WP_DIR_NAME }}\scripts\env.bat"
          pytest --pyargs ${{ env.LIB_TO_TEST }}

      - name: Upload Release Asset
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v0.1.7
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: ${{ env.asset_name }}
          prerelease: true


  finalise_release_job:
    needs: [build, build_portable]
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - name: Finalise release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions
        with:
          prerelease: false

